name: "Run tests"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - name: "Pypy 2.7"
            python-version: 'pypy-2.7'
            toxenv: 'pypy'
          - name: "Python 3.9"
            python-version: '3.9'
            toxenv: 'py3'
          - name: "Python 3.10"
            python-version: '3.10'
            toxenv: 'py3'
          - name: "Python 3.11"
            python-version: '3.11'
            toxenv: 'py3'
          - name: "Python 3.12"
            python-version: '3.12'
            toxenv: 'py3'
          - name: "Python 3.13"
            python-version: '3.13'
            toxenv: 'py3'
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Tests with tox
        env:
          TOXENV: ${{ matrix.toxenv }}
        run: |
          tox
      - name: Linting
        if: ${{ matrix.python-version==3.13 }}
        env:
          TOXENV: lint
        run: |
          tox
      - name: Run Codecov
        if: ${{ matrix.python-version==3.13 }}
        env:
          TOXENV: lint
        run: |
          pip install codecov
          codecov
      - name: Upload coverage to Codecov
        if: ${{ matrix.python-version==3.13 }}
        uses: codecov/codecov-action@v5

